version: '3'

services:
  nimble-taxi-client:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 9229:9229
      - 5000:5000
    command: npm run production